# -*- mode: ruby -*-
# vi: set ft=ruby :

IMAGE_NAME = "bento/fedora-34"
HOSTNAME = "jira-sandbox"

Vagrant.configure(2) do |config|

    #
    # Vagrantbox: jira-sandbox
    #
    config.vm.define HOSTNAME do |jira|
        jira.vm.box = IMAGE_NAME
        jira.vm.hostname = HOSTNAME

        # https://www.puppeteers.net/blog/fixing-vagrant-vbguest-for-the-centos-7-base-box/
        if Vagrant.has_plugin?("vagrant-vbguest")
            jira.vbguest.installer_options = { allow_kernel_upgrade: true }
        end

        jira.vm.provider "virtualbox" do |v|
            v.memory = 1024*4
            v.cpus = 1
            v.customize ["modifyvm", :id, "--groups", "/vagrantboxes"]
            v.name = HOSTNAME
        end

        # provisioning
        jira.vm.provision "shell", :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime", run: "always"
        jira.vm.provision "shell", path: "provision/configure.sh"
        jira.vm.provision "shell", path: "provision/install/update-upgrade.sh"
        jira.vm.provision "shell", path: "provision/install/git.sh"
        jira.vm.provision "shell", path: "provision/install/java.sh"
        jira.vm.provision "shell", path: "provision/install/zip.sh"
        jira.vm.provision "shell", path: "provision/jira-setup.sh"
        jira.vm.provision "shell", path: "services/jira-up.sh"

        jira.vm.network "forwarded_port", host: 8080, guest: 8080 # jira
    end
end
