= Step 8 - Configure HTTPS -> The broken attempt

To use HTTPS first you have to decide whether you want to use SSL termination or SSL passthrough. In this tutorial we use link:https://docs.digitalocean.com/products/networking/load-balancers/how-to/ssl-termination[SSL termination].

To avoid duplicate entries, define a variable which holds your domain name and add this to your `playground-provider.tf`:

[source, hcl-terraform]
----
# ...

variable "domain_fqdn" {
  type    = string
  default = "playground.cloud.sommerfeld.io"
}
----

Next, update your `playground-domain.tf` to pick up this domain name variable:

[source, hcl-terraform]
----
resource "digitalocean_domain" "cloud" {
  name       = var.domain_fqdn
  ip_address = digitalocean_loadbalancer.playground-lb.ip
}
----

Then configure a certificate from link:https://letsencrypt.org[let's encrypt]. To do this you have to add a "digitalocean_certificate" to your `playground-loadbalancer.tf`. Next the load balancer must accept incoming HTTPS connections. So set `entry_port = 443` and `entry_protocol = "https"` plus link the certificate via the `certificate_name` option.

The complete `playground-loadbalancer.tf` now looks like this:

[source, hcl-terraform]
----
resource "digitalocean_certificate" "cert" {
  name = "playground-cert" # when cert expires, do I need a new name here?
  type = "lets_encrypt"
  #domains = [digitalocean_domain.cloud.name]
  domains = [var.domain_fqdn]

  lifecycle {
    create_before_destroy = true
  }
}

resource "digitalocean_loadbalancer" "playground-lb" {
  name   = "playground-lb"
  region = "fra1"

  forwarding_rule {
    entry_port       = 443
    entry_protocol   = "https"
    target_port      = 80
    target_protocol  = "http"
    certificate_name = digitalocean_certificate.cert.name
  }

  healthcheck {
    port     = 22
    protocol = "tcp"
  }

  droplet_ids = [digitalocean_droplet.playground-www-1.id, digitalocean_droplet.playground-www-2.id]
}
----

Apply your configuration by running:

[source, bash]
----
terraform apply -var="do_token=<THE_DIGITAL_OCEAN_API_TOKEN>"
----

[IMPORTANT]
====
Current problem:

. using vars = domain for cert does not exist

[plantuml, rendered-plantuml-image, svg]
----
@startuml

skinparam linetype polyline
skinparam monochrome false
skinparam componentStyle uml2
skinparam backgroundColor transparent
skinparam ArrowColor black
skinparam FrameBackgroundColor #fff
skinparam CollectionsBackgroundColor #fefece
skinparam CollectionsBorderColor black
skinparam ComponentBorderColor black
skinparam ComponentBackgroundColor #fefece
skinparam RectangleBorderColor black
skinparam RectangleBackgroundColor #fefece
skinparam QueueBorderColor black
skinparam NoteBorderColor Grey
skinparam NoteBackgroundColor #fff
skinparam defaultTextAlignment center
skinparam activity {
  FontName Ubuntu
}

component lb as "digitalocean_loadbalancer.playground-lb"
component domain as "digitalocean_domain.cloud""
component cert as "digitalocean_certificate.cert""
component var as "var.fqdn"

cert -down-> lb
note right of lb: digitalocean_certificate.cert.name

var -right-> cert
var -left-> domain

label err as "domain for cert does not exist"

@enduml
----

[start=2]
. using `domains = [digitalocean_domain.cloud.name]` = Cycle: digitalocean_certificate.cert, digitalocean_loadbalancer.playground-lb, digitalocean_domain.cloud

[plantuml, rendered-plantuml-image, svg]
----
@startuml

skinparam linetype polyline
skinparam monochrome false
skinparam componentStyle uml2
skinparam backgroundColor transparent
skinparam ArrowColor black
skinparam FrameBackgroundColor #fff
skinparam CollectionsBackgroundColor #fefece
skinparam CollectionsBorderColor black
skinparam ComponentBorderColor black
skinparam ComponentBackgroundColor #fefece
skinparam RectangleBorderColor black
skinparam RectangleBackgroundColor #fefece
skinparam QueueBorderColor black
skinparam NoteBorderColor Grey
skinparam NoteBackgroundColor #fff
skinparam defaultTextAlignment center
skinparam activity {
  FontName Ubuntu
}

component lb as "digitalocean_loadbalancer.playground-lb"
component domain as "digitalocean_domain.cloud""
component cert as "digitalocean_certificate.cert""

lb -down-> domain
domain -right-> cert
note bottom of cert: digitalocean_domain.cloud.name
cert -up-> lb
note right of lb: digitalocean_certificate.cert.name

label err as "Cycle: digitalocean_certificate.cert,\ndigitalocean_loadbalancer.playground-lb,\ndigitalocean_domain.cloud"
note bottom of err: Everything depends on\neach other. Terraform does\nnot know what to create first.

@enduml
----

My StackOverflow Question: https://stackoverflow.com/questions/72196758/setup-domain-and-loadbalancer-with-https

====